import {
  BookOpenIcon,
  ChartPieIcon,
  CopyCheckIcon,
  CopyIcon,
  FolderKanbanIcon,
  HomeIcon,
  LayoutDashboardIcon,
  LifeBuoyIcon,
  LogOutIcon,
  PencilIcon,
  SettingsIcon,
  TrashIcon,
  UserIcon,
  UsersIcon,
} from 'lucide-react';

import type { Vendor } from '@/components/Columns';

export const VENDOR_BREAKDOWN = [
  { month: 'Jan 2025', asia: 35, us: 20, eu: 30 },
  { month: 'Feb 2025', asia: 30, us: 30, eu: 32 },
  { month: 'Mar 2025', asia: 24, us: 20, eu: 30 },
  { month: 'Apr 2025', asia: 28, us: 30, eu: 24 },
  { month: 'May 2025', asia: 10, us: 28, eu: 32 },
  { month: 'Jun 2025', asia: 13, us: 30, eu: 33 },
  { month: 'Jul 2025', asia: 10, us: 20, eu: 30 },
  { month: 'Aug 2025', asia: 20, us: 30, eu: 35 },
  { month: 'Sept 2025', asia: 10, us: 20, eu: 30 },
  { month: 'Oct 2025', asia: 28, us: 30, eu: 20 },
  { month: 'Nov 2025', asia: 24, us: 30, eu: 30 },
  { month: 'Dec 2025', asia: 35, us: 40, eu: 20 },
];

export const VENDOR_MONITORED = [{ year: '2025', monitored: 240, limit: 60 }];

export const APP_SIDEBAR = {
  primaryNav: [
    {
      title: 'Home',
      url: '#',
      Icon: HomeIcon,
    },
    {
      title: 'Dashboard',
      url: '#',
      Icon: LayoutDashboardIcon,
    },
    {
      title: 'Project',
      url: '#',
      Icon: FolderKanbanIcon,
    },
    {
      title: 'Tasks',
      url: '#',
      Icon: CopyCheckIcon,
    },
    {
      title: 'Reporting',
      url: '#',
      Icon: ChartPieIcon,
    },
    {
      title: 'Users',
      url: '#',
      Icon: UsersIcon,
    },
  ],
  secondaryNav: [
    {
      title: 'Support',
      url: '#',
      Icon: LifeBuoyIcon,
    },
    {
      title: 'Settings',
      url: '#',
      Icon: SettingsIcon,
    },
  ],
  curProfile: {
    src: 'https://randomuser.me/api/portraits/men/47.jpg',
    name: 'Salvador Pearson',
    email: 'salvador.pearson@example.com',
  },
  allProfiles: [
    {
      src: 'https://randomuser.me/api/portraits/men/47.jpg',
      name: 'Salvador Pearson',
      email: 'salvador.pearson@example.com',
    },
    {
      src: 'https://randomuser.me/api/portraits/women/43.jpg',
      name: 'Violet Hicks',
      email: 'violet.hicks@example.com',
    },
  ],
  userMenu: {
    itemsPrimary: [
      {
        title: 'View profile',
        url: '#',
        Icon: UserIcon,
        kbd: '⌘K->P',
      },
      {
        title: 'Account settings',
        url: '#',
        Icon: SettingsIcon,
        kbd: '⌘S',
      },
      {
        title: 'Documentation',
        url: '#',
        Icon: BookOpenIcon,
      },
    ],
    itemsSecondary: [
      {
        title: 'Sign out',
        url: '#',
        Icon: LogOutIcon,
        kbd: '⌥⇧Q',
      },
    ],
  },
};

export const DASHBOARD_CARD_MENU = [
  {
    label: 'Edit',
    Icon: PencilIcon,
  },
  {
    label: 'Copy',
    Icon: CopyIcon,
  },
  {
    label: 'Delete',
    Icon: TrashIcon,
  },
];

export const VENDOR_MOVEMENTS: Vendor[] = [
  {
    src: 'https://www.google.com/s2/favicons?domain=aws.amazon.com&sz=128',
    name: 'AWS',
    website: 'aws.amazon.com',
    rating: 94,
    ratingGrowthPercent: 2,
    lastAssessed: 'Jan 26, 2025',
    categories: ['Active', 'Database access', 'Admin', 'SOC2', 'Business data'],
  },
  {
    src: 'https://www.google.com/s2/favicons?domain=salesforce.com&sz=128',
    name: 'Salesforce',
    website: 'salesforce.com',
    rating: 88,
    ratingGrowthPercent: -1,
    lastAssessed: 'Jan 18, 2025',
    categories: [
      'Active',
      'Salesforce',
      'Customer data',
      'Financials',
      'Admin',
    ],
  },
  {
    src: 'https://www.google.com/s2/favicons?domain=stripe.com&sz=128',
    name: 'Stripe',
    website: 'stripe.com',
    rating: 96,
    ratingGrowthPercent: 5,
    lastAssessed: 'Jan 28, 2025',
    categories: ['Active', 'Financials', 'SOC2', 'Customer data'],
  },
  {
    src: 'https://www.google.com/s2/favicons?domain=slack.com&sz=128',
    name: 'Slack',
    website: 'slack.com',
    rating: 72,
    ratingGrowthPercent: -3,
    lastAssessed: 'Jan 22, 2025',
    categories: ['Active', 'Business data', 'Admin'],
  },
  {
    src: 'https://www.google.com/s2/favicons?domain=linear.app&sz=128',
    name: 'Linear',
    website: 'linear.app',
    rating: 91,
    ratingGrowthPercent: 12,
    lastAssessed: 'Jan 16, 2025',
    categories: ['Active', 'Business data', 'SOC2'],
  },
  {
    src: 'https://www.google.com/s2/favicons?domain=github.com&sz=128',
    name: 'GitHub',
    website: 'github.com',
    rating: 85,
    ratingGrowthPercent: 4,
    lastAssessed: 'Jan 20, 2025',
    categories: ['Active', 'Database access', 'Admin', 'SOC2'],
  },
  {
    src: 'https://www.google.com/s2/favicons?domain=notion.so&sz=128',
    name: 'Notion',
    website: 'notion.so',
    rating: 78,
    ratingGrowthPercent: 6,
    lastAssessed: 'Jan 24, 2025',
    categories: ['Active', 'Business data', 'Customer data'],
  },
  {
    src: 'https://www.google.com/s2/favicons?domain=figma.com&sz=128',
    name: 'Figma',
    website: 'figma.com',
    rating: 89,
    ratingGrowthPercent: 8,
    lastAssessed: 'Jan 30, 2025',
    categories: ['Active', 'Business data', 'Admin'],
  },
  {
    src: 'https://www.google.com/s2/favicons?domain=hubspot.com&sz=128',
    name: 'HubSpot',
    website: 'hubspot.com',
    rating: 65,
    ratingGrowthPercent: -2,
    lastAssessed: 'Jan 12, 2025',
    categories: ['Active', 'Customer data', 'Salesforce', 'Financials'],
  },
  {
    src: 'https://www.google.com/s2/favicons?domain=okta.com&sz=128',
    name: 'Okta',
    website: 'okta.com',
    rating: 92,
    ratingGrowthPercent: 1,
    lastAssessed: 'Feb 01, 2025',
    categories: ['Active', 'Admin', 'SOC2', 'Database access', 'Business data'],
  },
  {
    src: 'https://www.google.com/s2/favicons?domain=zoom.us&sz=128',
    name: 'Zoom',
    website: 'zoom.us',
    rating: 48,
    ratingGrowthPercent: -5,
    lastAssessed: 'Jan 15, 2025',
    categories: ['Inactive', 'Business data'],
  },
  {
    src: 'https://www.google.com/s2/favicons?domain=zendesk.com&sz=128',
    name: 'Zendesk',
    website: 'zendesk.com',
    rating: 62,
    ratingGrowthPercent: -1,
    lastAssessed: 'Jan 29, 2025',
    categories: ['Active', 'Customer data', 'Admin'],
  },
  {
    src: 'https://www.google.com/s2/favicons?domain=datadoghq.com&sz=128',
    name: 'Datadog',
    website: 'datadoghq.com',
    rating: 77,
    ratingGrowthPercent: 4,
    lastAssessed: 'Jan 25, 2025',
    categories: ['Active', 'Database access', 'Admin', 'SOC2'],
  },
  {
    src: 'https://www.google.com/s2/favicons?domain=adobe.com&sz=128',
    name: 'Adobe Creative Cloud',
    website: 'adobe.com',
    rating: 55,
    ratingGrowthPercent: 0,
    lastAssessed: 'Jan 10, 2025',
    categories: ['Active', 'Business data'],
  },
  {
    src: 'https://www.google.com/s2/favicons?domain=vercel.com&sz=128',
    name: 'Vercel',
    website: 'vercel.com',
    rating: 98,
    ratingGrowthPercent: 10,
    lastAssessed: 'Feb 02, 2025',
    categories: ['Active', 'Database access', 'Admin', 'SOC2'],
  },
  {
    src: 'https://www.google.com/s2/favicons?domain=atlassian.com&sz=128',
    name: 'Atlassian (Jira)',
    website: 'atlassian.com',
    rating: 58,
    ratingGrowthPercent: -4,
    lastAssessed: 'Jan 19, 2025',
    categories: ['Active', 'Business data', 'Admin'],
  },
  {
    src: 'https://www.google.com/s2/favicons?domain=snowflake.com&sz=128',
    name: 'Snowflake',
    website: 'snowflake.com',
    rating: 84,
    ratingGrowthPercent: 3,
    lastAssessed: 'Jan 31, 2025',
    categories: [
      'Active',
      'Database access',
      'Financials',
      'SOC2',
      'Customer data',
    ],
  },
  {
    src: 'https://www.google.com/s2/favicons?domain=miro.com&sz=128',
    name: 'Miro',
    website: 'miro.com',
    rating: 71,
    ratingGrowthPercent: 3,
    lastAssessed: 'Jan 21, 2025',
    categories: ['Active', 'Business data'],
  },
  {
    src: 'https://www.google.com/s2/favicons?domain=oracle.com&sz=128',
    name: 'Oracle',
    website: 'oracle.com',
    rating: 44,
    ratingGrowthPercent: -5,
    lastAssessed: 'Jan 14, 2025',
    categories: ['Inactive', 'Database access', 'Financials'],
  },
  {
    src: 'https://www.google.com/s2/favicons?domain=intercom.com&sz=128',
    name: 'Intercom',
    website: 'intercom.com',
    rating: 67,
    ratingGrowthPercent: 2,
    lastAssessed: 'Jan 27, 2025',
    categories: ['Active', 'Customer data', 'Salesforce'],
  },
  {
    src: 'https://www.google.com/s2/favicons?domain=auth0.com&sz=128',
    name: 'Auth0',
    website: 'auth0.com',
    rating: 88,
    ratingGrowthPercent: 1,
    lastAssessed: 'Jan 23, 2025',
    categories: ['Active', 'Admin', 'SOC2', 'Customer data'],
  },
  {
    src: 'https://www.google.com/s2/favicons?domain=dropbox.com&sz=128',
    name: 'Dropbox',
    website: 'dropbox.com',
    rating: 60,
    ratingGrowthPercent: -2,
    lastAssessed: 'Jan 17, 2025',
    categories: ['Active', 'Business data', 'Admin'],
  },
  {
    src: 'https://www.google.com/s2/favicons?domain=cloudflare.com&sz=128',
    name: 'Cloudflare',
    website: 'cloudflare.com',
    rating: 95,
    ratingGrowthPercent: 7,
    lastAssessed: 'Jan 29, 2025',
    categories: ['Active', 'Admin', 'SOC2', 'Database access'],
  },
  {
    src: 'https://www.google.com/s2/favicons?domain=1password.com&sz=128',
    name: '1Password',
    website: '1password.com',
    rating: 93,
    ratingGrowthPercent: 4,
    lastAssessed: 'Feb 03, 2025',
    categories: ['Active', 'Admin', 'SOC2', 'Business data'],
  },
  {
    src: 'https://www.google.com/s2/favicons?domain=asana.com&sz=128',
    name: 'Asana',
    website: 'asana.com',
    rating: 70,
    ratingGrowthPercent: -1,
    lastAssessed: 'Jan 13, 2025',
    categories: ['Active', 'Business data'],
  },
  {
    src: 'https://www.google.com/s2/favicons?domain=box.com&sz=128',
    name: 'Box',
    website: 'box.com',
    rating: 52,
    ratingGrowthPercent: -3,
    lastAssessed: 'Jan 11, 2025',
    categories: ['Inactive', 'Business data', 'Admin'],
  },
  {
    src: 'https://www.google.com/s2/favicons?domain=mailchimp.com&sz=128',
    name: 'Mailchimp',
    website: 'mailchimp.com',
    rating: 68,
    ratingGrowthPercent: 1,
    lastAssessed: 'Jan 26, 2025',
    categories: ['Active', 'Customer data', 'Salesforce'],
  },
  {
    src: 'https://www.google.com/s2/favicons?domain=workday.com&sz=128',
    name: 'Workday',
    website: 'workday.com',
    rating: 74,
    ratingGrowthPercent: 2,
    lastAssessed: 'Jan 19, 2025',
    categories: ['Active', 'Financials', 'Admin', 'Business data'],
  },
  {
    src: 'https://www.google.com/s2/favicons?domain=mongodb.com&sz=128',
    name: 'MongoDB Atlas',
    website: 'mongodb.com',
    rating: 86,
    ratingGrowthPercent: 5,
    lastAssessed: 'Jan 24, 2025',
    categories: ['Active', 'Database access', 'SOC2', 'Admin'],
  },
  {
    src: 'https://www.google.com/s2/favicons?domain=sentry.io&sz=128',
    name: 'Sentry',
    website: 'sentry.io',
    rating: 82,
    ratingGrowthPercent: 3,
    lastAssessed: 'Jan 28, 2025',
    categories: ['Active', 'Admin', 'SOC2'],
  },
  {
    src: 'https://www.google.com/s2/favicons?domain=digitalocean.com&sz=128',
    name: 'DigitalOcean',
    website: 'digitalocean.com',
    rating: 76,
    ratingGrowthPercent: 2,
    lastAssessed: 'Jan 15, 2025',
    categories: ['Active', 'Database access', 'Admin'],
  },
  {
    src: 'https://www.google.com/s2/favicons?domain=godaddy.com&sz=128',
    name: 'GoDaddy',
    website: 'godaddy.com',
    rating: 45,
    ratingGrowthPercent: -8,
    lastAssessed: 'Jan 10, 2025',
    categories: ['Inactive', 'Admin'],
  },
  {
    src: 'https://www.google.com/s2/favicons?domain=bamboohr.com&sz=128',
    name: 'BambooHR',
    website: 'bamboohr.com',
    rating: 79,
    ratingGrowthPercent: 4,
    lastAssessed: 'Feb 01, 2025',
    categories: ['Active', 'Business data', 'Financials'],
  },
  {
    src: 'https://www.google.com/s2/favicons?domain=gong.io&sz=128',
    name: 'Gong',
    website: 'gong.io',
    rating: 81,
    ratingGrowthPercent: 6,
    lastAssessed: 'Jan 31, 2025',
    categories: ['Active', 'Salesforce', 'Customer data', 'Business data'],
  },
  {
    src: 'https://www.google.com/s2/favicons?domain=canva.com&sz=128',
    name: 'Canva',
    website: 'canva.com',
    rating: 90,
    ratingGrowthPercent: 8,
    lastAssessed: 'Jan 22, 2025',
    categories: ['Active', 'Business data'],
  },
  {
    src: 'https://www.google.com/s2/favicons?domain=pagerduty.com&sz=128',
    name: 'PagerDuty',
    website: 'pagerduty.com',
    rating: 73,
    ratingGrowthPercent: -1,
    lastAssessed: 'Jan 18, 2025',
    categories: ['Active', 'Admin', 'SOC2'],
  },
  {
    src: 'https://www.google.com/s2/favicons?domain=circleci.com&sz=128',
    name: 'CircleCI',
    website: 'circleci.com',
    rating: 64,
    ratingGrowthPercent: -4,
    lastAssessed: 'Jan 14, 2025',
    categories: ['Active', 'Database access', 'Admin'],
  },
  {
    src: 'https://www.google.com/s2/favicons?domain=docusign.com&sz=128',
    name: 'DocuSign',
    website: 'docusign.com',
    rating: 83,
    ratingGrowthPercent: 2,
    lastAssessed: 'Jan 27, 2025',
    categories: ['Active', 'Business data', 'Financials', 'Legal'],
  },
  {
    src: 'https://www.google.com/s2/favicons?domain=shopify.com&sz=128',
    name: 'Shopify',
    website: 'shopify.com',
    rating: 87,
    ratingGrowthPercent: 5,
    lastAssessed: 'Jan 25, 2025',
    categories: ['Active', 'Financials', 'Customer data', 'SOC2'],
  },
  {
    src: 'https://www.google.com/s2/favicons?domain=gitlab.com&sz=128',
    name: 'GitLab',
    website: 'gitlab.com',
    rating: 80,
    ratingGrowthPercent: 3,
    lastAssessed: 'Jan 20, 2025',
    categories: ['Active', 'Database access', 'Admin', 'SOC2'],
  },
  {
    src: 'https://www.google.com/s2/favicons?domain=segment.com&sz=128',
    name: 'Segment',
    website: 'segment.com',
    rating: 75,
    ratingGrowthPercent: 1,
    lastAssessed: 'Jan 23, 2025',
    categories: ['Active', 'Customer data', 'Database access', 'Salesforce'],
  },
  {
    src: 'https://www.google.com/s2/favicons?domain=twilio.com&sz=128',
    name: 'Twilio',
    website: 'twilio.com',
    rating: 69,
    ratingGrowthPercent: -2,
    lastAssessed: 'Jan 16, 2025',
    categories: ['Active', 'Customer data', 'Admin'],
  },
  {
    src: 'https://www.google.com/s2/favicons?domain=intuit.com&sz=128',
    name: 'QuickBooks',
    website: 'intuit.com',
    rating: 63,
    ratingGrowthPercent: -1,
    lastAssessed: 'Jan 12, 2025',
    categories: ['Active', 'Financials', 'Business data'],
  },
  {
    src: 'https://www.google.com/s2/favicons?domain=mural.co&sz=128',
    name: 'Mural',
    website: 'mural.co',
    rating: 59,
    ratingGrowthPercent: 0,
    lastAssessed: 'Jan 19, 2025',
    categories: ['Active', 'Business data'],
  },
  {
    src: 'https://www.google.com/s2/favicons?domain=airtable.com&sz=128',
    name: 'Airtable',
    website: 'airtable.com',
    rating: 84,
    ratingGrowthPercent: 7,
    lastAssessed: 'Feb 02, 2025',
    categories: ['Active', 'Database access', 'Business data', 'Admin'],
  },
  {
    src: 'https://www.google.com/s2/favicons?domain=loom.com&sz=128',
    name: 'Loom',
    website: 'loom.com',
    rating: 88,
    ratingGrowthPercent: 9,
    lastAssessed: 'Jan 28, 2025',
    categories: ['Active', 'Business data'],
  },
  {
    src: 'https://www.google.com/s2/favicons?domain=framer.com&sz=128',
    name: 'Framer',
    website: 'framer.com',
    rating: 79,
    ratingGrowthPercent: 6,
    lastAssessed: 'Jan 30, 2025',
    categories: ['Active', 'Business data', 'Admin'],
  },
  {
    src: 'https://www.google.com/s2/favicons?domain=deel.com&sz=128',
    name: 'Deel',
    website: 'deel.com',
    rating: 92,
    ratingGrowthPercent: 11,
    lastAssessed: 'Jan 21, 2025',
    categories: ['Active', 'Financials', 'SOC2', 'Admin'],
  },
  {
    src: 'https://www.google.com/s2/favicons?domain=freshworks.com&sz=128',
    name: 'Freshworks',
    website: 'freshworks.com',
    rating: 56,
    ratingGrowthPercent: -3,
    lastAssessed: 'Jan 13, 2025',
    categories: ['Inactive', 'Customer data', 'Admin'],
  },
  {
    src: 'https://www.google.com/s2/favicons?domain=zapier.com&sz=128',
    name: 'Zapier',
    website: 'zapier.com',
    rating: 81,
    ratingGrowthPercent: 2,
    lastAssessed: 'Jan 17, 2025',
    categories: [
      'Active',
      'Admin',
      'Salesforce',
      'Database access',
      'Business data',
    ],
  },
];